### ISSUE TITLE
Changing attribute value doesn't trigger re-render

### ISSUE THREAD

**Issue by tbashor** [OutwalkStudios/exalt#12]
According to the documentation, changing an attribute should trigger a re-render. I'm unable to trigger a re-render when programmatically changing the attribute. 

Using the this tag:
`<say-hello id="hello" name="John Doe" />`

with this definition:
```
import { Component, html } from "@exalt/core";
import { define } from "@exalt/core/decorators";

@define("say-hello")
export class SayHello extends Component {

    render({ name }) {
        return html`
            <h1>Hello ${name}!</h1>
        `;
    }
}
```

In a different script, I run this after the say-hello element is fully rendered.
```
let hello = document.getElementById('hello')
hello.setAttribute('name', 'Another Name')
```

I can see that the name attribute on the element changes, but the text on the page still says "Hello John Doe". Can you explain how to get the component to react properly to the attribute change?

**Comment by jleeson** [comment]
Hello, sorry you ran into this issue. Exalt currently is not watching attribute changes directly, instead it reads attributes when created and puts them into a Proxy in order to monitor changes. This is where the `props` property is used. We are currently working on planning out the best way to improve compatibility with existing frameworks and apis which should resolve this issue. In the meantime you can get the component to react by modifying the props object directly. 

```js
let hello = document.getElementById('hello')
hello.props.name = "Another Name";
```

If you prefer declaratively attribute changes are checked during exalt template compilation.
So if the parent component is passing a variable as the name attribute and that variable changes, and triggers a re-render the say-hello component will detect the change and also re-render.

```js
const name = "John Doe";
html`<say-hello id="hello" name=${name} />`;
```

**Comment by tbashor** [comment]
Very helpful, thanks. Any idea when the attributes themselves will be watched?

**Comment by jleeson** [comment]
No problem, We are aiming to have an update out around February that will resolve this issue as well as compatibility with other frameworks. Its possible this could be resolved before then as well. I also will update this issue when a fix is released.

**Comment by jleeson** [comment]
Thank you for bringing this issue to our attention @tbashor! Thankfully we got a solution implemented quicker than we had planned and now your original code should work if you update @exalt/core to v1.1.5. This connects the components setAttribute and removeAttribute methods to the reactivity engine. Our update planned for a few months from now will resolve more overall compatibility challenges with other frameworks and component libraries. For now this should resolve this issue. If you run into any more problems feel free to open another issue!
